[package]
name = "helpscout"
version = "0.0.1"
authors = ["Lance Carlson <lancecarlson@gmail.com>", "Tristan Mortimer <tristan.e.mortimer@gmail.com>"]
description = "Bindings for the HelpScout API."
license = "MIT"

[dependencies]
reqwest = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
dotenv = "0.10"
time = "0.1"